---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-addons
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: istio-project
  source:
    path: ./manifests/istio-1-14-1/addons/
    repoURL: git@github.com:<ORG>/<REPO>.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
    syncOptions:
    - CreateNamespace=false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-metrics-expose
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: istio-project
  source:
    path: ./manifests/istio-1-14-1/logging/
    repoURL: git@github.com:<ORG>/<REPO>.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
    syncOptions:
    - CreateNamespace=false
