# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name:  tools-kube-prometheus-stack-crds
#   namespace: argocd
# spec:
#   destination:
#     namespace: tools
#     server: https://kubernetes.default.svc
#   project: default
#   source:
#     repoURL: https://github.com/prometheus-community/helm-charts.git
#     path: charts/kube-prometheus-stack/crds/
#     targetRevision: kube-prometheus-stack-39.11.0
#     directory:
#       recurse: true
#   syncPolicy:
#     automated:
#       selfHeal: false
#       prune: true
#     syncOptions:
#     - CreateNamespace=false
#     - Replace=true
