
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tools-pgadmin
  namespace: argocd                                # Namespace in which ArgoCD is deployed
spec:
  destination:
    namespace: tools
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://helm.runix.net'
    targetRevision: 1.9.9
    helm:
      parameters:
        - name: serverDefinitions.servers
          value: ' {        "Servers": {          "1": {            "Name": "Azure PostgreSQL-DB",            "Group": "Servers",            "Port": 5432,            "Username": "psqladmin@postgresrpdev2.postgres.database.azure.com",            "Host": "postgresrpdev2.postgres.database.azure.com",            "SSLMode": "prefer",            "MaintenanceDB": "postgres"          }        }    }'
        - name: serverDefinitions.enabled
          value: 'false'
    chart: pgadmin4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true