apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tools-azure-monitor
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/azure-monitor/
    repoURL: git@github.com:<ORG>/<REPO>.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
    syncOptions:
    - CreateNamespace=false