global.additionalLabels:
  - "argocd.argoproj.io/instance": "argocd"

redis-ha:
  enabled: false 
  haproxy:
    image:
      repository: haproxy
      tag: 2.4.9

controller:
  replicas: 1
  enableStatefulSet: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels: #key and label can be changed via: https://github.com/prometheus-community/helm-charts/blob/864a266c962873b1ea21da91e11faa4bea7fa223/charts/kube-prometheus-stack/values.yaml#L2229
        release: prometheus

server:
  autoscaling:
    enabled: true
    minReplicas: 2
  configEnabled: true
  config:
    repositories: |
      - url: git@github.com:<ORG>/<REPO>.git
        name: main-repositroy
        sshPrivateKeySecret:
          name: github-main-repo-secret
          key: ssh-privatekey
      
# -- Bcrypt hashed admin password
## Argo expects the password in the secret to be bcrypt hashed. You can create this hash with
#
## 1.Install htpasswd: sudo apt-get install apache2-utils
## `htpasswd -nbBC 10 "" $ARGO_PWD | tr -d ':\n' | sed 's/$2y/$2a/'`
# TODO: Helper Function/ GH Action to generate bcrypt hashed Passwords from Workflow Trigger Inputs
configs.secret.argocdServerAdminPassword: "$2a$10$PiORlu8F6P7k2lXT1xfnRO/gcDkDmP68OJLm7h5siCtKEvwQAy6ky"

# configs:
#   knownHosts:
#     data:
#       ssh_known_hosts: |-
#         |1|I7sWUOhC/cavJZVcmr8RnkaIxaA=|h4pf70Uf0GUyYRVKyO+uX9CwSwA= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
#         |1|QrwWD43rKswO1gcOUJOPA8MzWDg=|xeuOJHdKXyJB9u0TW3jIkSFVJQM= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
#         |1|TUFASjkt6KqQNwKYvD0yKP7Kl8w=|zs6wXWJK5ThS0O4Z9LZkAOSHVxQ= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=
#         |1|Ft0Uyx7yOTdzEnotBJzJlQc000o=|Bp7GVXbxQVKqLesr+yoYmjTogzA= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=
#         |1|S6saI0njbWeZHd8KRAzyheRImZY=|Lte3jwAg65edypG9gmpzdxQookk= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
#         |1|WICX3E2atVO53cBwGc7UIj+LAgo=|eB4ZFNyB4r+YL26CnsLO7qFXx9c= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
#         |1|BBWzvbKQdBDDBdxbxnJjxAkU35o=|AthjzRoXl+8LKa/TkjP67Anp2Fk= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=


repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
    # https://faun.pub/deploying-argo-cd-and-sealed-secrets-with-helm-8de12f53051b

applicationSet:
  replicaCount: 2