apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: test123@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsZones:
          - "my-domain.de"
      dns01:
        azureDNS:
          clientID: <clientID>
          clientSecretSecretRef:
          # The following is the secret we created in Kubernetes. Issuer will use this to present challenge to Azure DNS.
          # Create with: kubectl create secret generic azuredns-config --from-literal=client-secret=<client-secret>
            name: azuredns-config
            key: client-secret
          subscriptionID: <subscriptionID>
          tenantID: <tenantID>
          resourceGroupName: <resourceGroupName>
          hostedZoneName: "my-domain.de"
          # Azure Cloud Environment, default to AzurePublicCloud
          environment: AzurePublicCloud
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert-wild
  namespace: istio-system
spec:
  secretName: ingress-cert-wild
  commonName: "*.my-domain.de"
  issuerRef: 
    kind: Issuer
    name: letsencrypt-prod
  dnsNames:
  - "*.my-domain.de"
---